# Setup
title:        Digi Wombat
tagline:      A technical blog about coding, software engineering, continous integration, system architecture and life.
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Bob Huang
  url:        http://blog.angrywombat.net

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
